### ISSUE TITLE
Specify the plugin source in the wp-package.json

### ISSUE THREAD

**Issue by gardenboi** [erikyo/wpmm#3]
to avoid conflicts or issues of any kind we could add an opional field that will correspond to the github url so the program will clone the repo directly from github instead of guessing the source of the plugin, that way the user can avoid conflicts if the plugin is present both in wp repo or github repo

**Comment by erikyo** [comment]
yep that right, good catch. would be cool because in this way we can also add other "way" to download the package like the git clone.

the oop refactor (checkout the new branch) will help with this job, give a look and let me know is it's feasible
